x-deploy: &x-deploy-default
  replicas: 3
  placement:
    max_replicas_per_node: 1
    constraints:
      - node.labels.mimir == true
    preferences:
      - spread: node.labels.mimir
  update_config:
    parallelism: 1
    delay: 30s
    order: stop-first
    failure_action: rollback
  rollback_config:
    parallelism: 1
    delay: 30s
  restart_policy:
    condition: on-failure
    delay: 30s
    max_attempts: 3
    window: 120s

x-logging: &x-logging-default
  options:
    max-size: "12m"
    max-file: "5"
  driver: json-file

networks:
  dockerswarm_monitoring:
    name: dockerswarm_monitoring
    external: true

volumes:
  mimir:
    external: true

configs:
  mimir.yaml:
    template_driver: golang
    file: configs/mimir.yaml
  alertmanager-fallback-config.yaml:
    file: configs/alertmanager-fallback-config.yaml

services:
  mimir:
    image: grafana/mimir:${GRAFANA_MIMIR_VERSION:-latest}
    command: 
      - -config.expand-env=true
      - -config.file=/etc/mimir/mimir.yaml
    networks:
      - dockerswarm_monitoring
    ports:
      - ${GRAFANA_MIMIR_PORT:-3200}:3200 # http
      # - 9097:9097 # grpc
    volumes:
      - mimir:/mimir
    configs:
      - source: mimir.yaml
        target: /etc/mimir/mimir.yaml
      - source: alertmanager-fallback-config.yaml
        target: /etc/mimir/alertmanager-fallback-config.yaml
    deploy: *x-deploy-default
    logging: *x-logging-default
